import React from 'react'
import Head from 'next/head'
import { useQuery } from '@apollo/client'

import Header from '@/components/header'
import MapboxMap from '@/components/mapbox-map'
import SuggestedMeets from '@/components/suggested-meets'
import Footer from '@/components/footer'
import { GetEmployeesDocument } from '../generated'
import AllEmployees from '@/components/all-employees'
import MenuNav from '@/components/menu-nav'

const ConnectedHomePage = () => {
  const { data } = useQuery(GetEmployeesDocument, {
    variables: { filter: '', sort: 2 },
    nextFetchPolicy: 'cache-first',
  })

  return (
    <div className='w-full'>
      <Header />

      <div>
        <div className='flex justify-center sticky top-0 z-20'>
          <MenuNav />
        </div>

        <div
          className='h-full'
          style={{ background: 'linear-gradient(rgba(0,0,0,0.1),#FFF)' }}
        >
          <Head>
            <title>YouMeet</title>
            <meta name='description' content='Generated by create next app' />

            <link rel='icon' href='/logo-favicon.png' />
          </Head>
          <div className='h-[48px]' />
          <div className='w-full flex justify-center'>
            <MapboxMap
              center={[3, 33]}
              zoom={1.5}
              employees={data?.employees}
              styles={{
                width: '80%',
                minHeight: '800px',
                margin: 20,
                borderRadius: 20,
                border: '1px solid black',
              }}
            />
          </div>
          <SuggestedMeets data={data} />
          <AllEmployees />
        </div>
      </div>
      <Footer />
    </div>
  )
}

export default ConnectedHomePage
