/* eslint-disable react-hooks/rules-of-hooks */
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useSelector } from 'react-redux'
import { useEffect, useState } from 'react'
import { ClipLoader } from 'react-spinners'
import { useQuery } from '@apollo/client'
import { signIn, useSession } from 'next-auth/react'

import { withProtected } from '../components/route-protection'
import { RootState } from '../redux/store'
import Header from '../components/header'
import { GetEmployees } from '../apollo/queries'
import MapboxMap from '../components/mapbox-map'
import EmployeesList from '../components/employees-list'
import Footer from '../components/footer'

const Home: NextPage = () => {
  const username = useSelector((state: RootState) => state.user.username)
  const router = useRouter()
  const [authenticated, setAuthenticated] = useState(username ? true : false)
  const { data } = useQuery(GetEmployees)
  const { data: session } = useSession()

  useEffect(() => {
    if (!session) {
      // signIn()
      router.push('/login')
    }
  }, [])
  console.log('line 29', data)
  return session && data ? (
    <div className="h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div
        className="w-full flex justify-center mt-16"
        style={{ background: 'linear-gradient(rgba(0,0,0,0.1),#FFF)' }}
      >
        <MapboxMap employees={data.employees} />
      </div>
      <EmployeesList data={data} />
      <Footer />
    </div>
  ) : (
    <div className="w-full h-full flex justify-center items-center">
      <ClipLoader size={66} />
    </div>
  )
}

export default Home
// export default withProtected(Home);
