import React, { lazy, Suspense } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useQuery } from '@apollo/client'
import { useAuth0 } from '@auth0/auth0-react'
import Image from 'next/future/image'

import Header from '@/components/header'
import MapboxMap from '@/components/mapbox-map'
import SuggestedMeets from '@/components/suggested-meets'
import Footer from '@/components/footer'
import { GetEmployeesDocument } from '../generated'
import AllEmployees from '@/components/all-employees'
import Hero from '@/components/hero'
import LinkCTA from '@/components/link-CTA'
import hero from '../public/hero2.jpg'
import MenuNav from '@/components/menu-nav'

const MarketingCard = lazy(() => import('@/components/marketing-card'))

const Home: NextPage = () => {
  const { data } = useQuery(GetEmployeesDocument, {
    variables: { filter: '', sort: 2 },
    nextFetchPolicy: 'cache-first',
  })
  const { user, isAuthenticated } = useAuth0()

  return (
    <div className='w-full'>
      <Header />
      {isAuthenticated && user ? (
        <div>
          <div className='flex justify-center sticky top-0 z-20'>
            <MenuNav />
          </div>

          <div
            className='h-full'
            style={{ background: 'linear-gradient(rgba(0,0,0,0.1),#FFF)' }}
          >
            <Head>
              <title>YouMeet</title>
              <meta name='description' content='Generated by create next app' />
              <link rel='icon' href='/logo-favicon.png' />
            </Head>
            <div className='h-[48px]' />
            <div className='w-full flex justify-center'>
              <MapboxMap
                center={[3, 33]}
                zoom={1.5}
                employees={data?.employees}
                styles={{
                  width: '80%',
                  minHeight: '800px',
                  margin: 20,
                  borderRadius: 20,
                  border: '1px solid black',
                }}
              />
            </div>
            <SuggestedMeets data={data} />
            <AllEmployees />
          </div>
        </div>
      ) : (
        <div className='h-full flex flex-col justify-center items-center'>
          <div className='flex justify-center w-[90%] min-h-[350px] bg-[#2F1781] appear-slowly my-[20px] rounded relative'>
            <div className='flex justify-center items-center absolute z-0'>
              <Image
                src={hero}
                width={500}
                height={350}
                className='h-[350px] w-[540px]'
              />
            </div>

            <div className='flex justify-between items-center flex-1 relative'>
              <Hero />
            </div>
            <div className='web2:flex-1 mobile3:w-[60px]' />
            <LinkCTA />
          </div>
          <div className='bg-gray-100 w-[90%] rounded'>
            {[1, 2].map((card) => (
              <div key={card}>
                <Suspense fallback={<div>Chargement..</div>}>
                  <MarketingCard
                    firstComp={card % 2 === 0 ? 'text' : 'img'}
                    src={`../public/people${card}.jpg`}
                    card={card}
                  />
                </Suspense>
              </div>
            ))}
          </div>
        </div>
      )}
      <Footer />
    </div>
  )
}

export default Home
